# Edit this file to add dependencies to environment,
# Then run `./lock-environment.sh` to generate reproducible lock files

# !!! If you are developing the website locally use the existing lock files
# for your platform (`conda create --name hackweek --file conda-osx-64.lock`)
name: hackweek
channels:
  - conda-forge
dependencies:
  # Common
  - python=3.10
  - pip
  # JupyterBook
  - cookiecutter
  - jinja2>=2.11
  - pygments>=2.6.1
  - pymdown-extensions>=7.1
  - sphinxcontrib-bibtex
  # User Interface
  - jupyterlab=3
  - jupyter-resource-usage
  - jupyterhub-singleuser
  - gh-scoped-creds
  # Analysis
  - cartopy
  - datashader
  - geopandas
  - geoviews
  - gh
  - git
  - h5py
  - hvplot
  - ipyleaflet
  - matplotlib
  - pyproj
  - rioxarray
  - s3fs
  - shapely
  - vim
  - wget
  - xarray 
  - zarr
  - pip:
    - jinja-markdown==1.210911
platforms:
  - linux-64
  - osx-64
